
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: job1
    steps:
      - bash: echo Build job1
      - bash: echo $(PipelineVariable)
      - bash: echo $(Build.BuildNumber)
      - bash: echo $(Build.BuildId)
      - bash: echo $(Build.SourceBranchName)
      - bash: java -version
      - bash: python --version
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: |
           **/*.yml
           **/*.tf
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
#   - job: job2
#     steps:
#       - bash: echo $(PipelineVariable) Build job2
# - stage: devDeploy
#   variables:
#     environment: dev
#   dependsOn: Build
#   jobs:
#   - job: devDeployjob
#     steps:
#       - bash: echo $(PipelineVariable) DevDeploy job

# - stage: qaDeploy
#   variables:
#     environment: Qa
#   dependsOn: devDeploy
#   jobs:
#   - job: qaDeployjob
#     steps:
#       - bash: echo $(PipelineVariable) QaDeploy job

# - stage: ProdDeploy
#   variables:
#     environment: Prod
#   dependsOn: qaDeploy
#   jobs:
#   - job: ProdDeployjob
#     steps:
#       - bash: echo $(PipelineVariable) ProdDeploy job
