
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: job1
    steps:
      - bash: echo Build job1
  - job: job2
    steps:
      - bash: echo Build job2
- stage: devDeploy
  dependsOn: Build
  jobs:
  - job: devDeployjob
    steps:
      - bash: echo DevDeploy job

- stage: qaDeploy
  dependsOn: devDeploy
  jobs:
  - job: qaDeployjob
    steps:
      - bash: echo QaDeploy job

- stage: ProdDeploy
  dependsOn: qaDeploy
  jobs:
  - job: ProdDeployjob
    steps:
      - bash: echo ProdDeploy job
