
trigger:
- main

# strategy:
#  matrix:
#    linux:
#      operatingsystem: 'ubuntu-latest'
#    mac:
#      operatingsystem: 'macos-latest' 

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildStage
    jobs:
    - job: BuildJob
      steps:
      -  bash: echo "Do The Build"
  - stage: Devstage
    jobs:
    - deployment: devDeployJob
      environment: Dev
      strategy:
       runOnce:
         deploy:
          steps:
            - script: echo deploy to Dev
  - stage: Qastage
    jobs:
    - deployment: QaDeployJOb
      environment: Qa
      strategy:
       runOnce:
         deploy:
          steps:
            - script: echo deploy to QA